[package]
name = "bench-rust"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "bench-rust"
path = "src/bench-rust.rs"

[dependencies]

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = 'abort' 